### ISSUE TITLE
repo dead?

### ISSUE THREAD

**Issue by graingert** [jd-boyd/sexpdata#12]
@tkf is this repo dead?

**Comment by jd-boyd** [comment]
I sent an email inquiring about transferring the pypi project if @tkf was no longer interested in it.  I never got a reply, so I've forked it, renamed it to pysexp, and will be releasing that, along with merging what outstanding work I can.

**Comment by graingert** [comment]
@jd-boyd fyi, if you've made the effort to contact the maintainers and they haven't got back to you, you can request that PyPI transfer the project to you

**Comment by jd-boyd** [comment]
In case this isn't broadcast, @tkf has agreed to transfer the repo to me as well as give me access to make new releases on pypi and readthedocs.  As soon as possible, I will be going through the issues and pull requests.
