### ISSUE TITLE
More "\" in dumps 

### ISSUE THREAD

**Issue by xuanlinhha** [jd-boyd/sexpdata#13]
Hi, can we disable ```'\'``` before ```'.'``` in the result?
```
>> print(dumps([Symbol('a.c'), Symbol('b')]))
(a\.c b)
```
I want to get the result ```a.c b```
Thanks,

**Comment by johanatan** [comment]
Having same issue here.

**Comment by Qbort** [comment]
Same here.

**Comment by vleni** [comment]
You would have to remove `('.', r'\.')` from `Symbol._lisp_quoted_specials`. I don't know why this even exists in the first place
