### ISSUE TITLE
Symbol to string

### ISSUE THREAD

**Issue by brando90** [jd-boyd/sexpdata#16]
how does one convert a symbol to a string? Like:

```
str(Symbol('App')) -> 'App'
```

is there a clean way to do this? Currently calling `str()` on symbol doesn't help and equalities like:

`term == 'App'`

fail.

**Comment by brando90** [comment]
do:

`term._val`

**Comment by jd-boyd** [comment]
> do:
> 
> `term._val`

Is there still a specific issue you would like fixed then, or can I close this?
