### ISSUE TITLE
checking is something is a valid s-expression

### ISSUE THREAD

**Issue by brando90** [jd-boyd/sexpdata#19]
I was getting the error documented https://github.com/jd-boyd/sexpdata/issues/18 and I wanted to check if it was if my string was a valid s-expression. Is there an automatic tool to check such a thing?

**Comment by immerrr** [comment]
I am using Emacs for this, but I suppose any decent online LISP compiler will do, you just need to quote the s-expression:
![image](https://user-images.githubusercontent.com/579798/56636292-92f9ff00-6668-11e9-95cc-aa5fdc54c60a.png)

**Comment by immerrr** [comment]
So for your particular case it would look like this: https://rextester.com/ZMXR77997

**Comment by jd-boyd** [comment]
It looks like this questions has been adequately answered.
