### ISSUE TITLE
advantages of sexpdata vs pyparsing s-expressions

### ISSUE THREAD

**Issue by brando90** [jd-boyd/sexpdata#20]
I just found that one can parse s-expressions using [pyparsing](https://github.com/pyparsing/pyparsing) using the example file [here](http://www.ccp4.ac.uk/dist/checkout/pyparsing-2.0.1/examples/sexpParser.py).

What are the advantages and disadvantages of using sexpdata vs pyparsing?

**Comment by immerrr** [comment]
sexpdata is a small package for parsing and serializing s-expressions, and that's it. pyparsing is a rather sizeable project to implement parsers for any context-free grammars (CFGs). 

Naturally s-expressions can be expressed as a CFG so they are covered by pyparsing too, so for the end user the differences mostly lie in performance (DISCLAIMER: I didn't benchmark this, but I'd expect a universal parser to be a tad slower than a specific one) and dependency size.

**Comment by jd-boyd** [comment]
@immerr do you think it would be worth adding this to the README?

**Comment by immerrr** [comment]
I am not against it, but I'm not sure I see the context of starting to speak about a different library in a rather short readme that only contains the most basic information, usage and such. I mean, if it were a more complex library and we had a multi-page doc explaining the design decisions, and tradeoffs and whatnot, it would definitely deserve a section to speak about alternatives, but probably sexpdata is not of such scale (yet).

**Comment by jd-boyd** [comment]
OK, then I think this is ready to close.  Someone can re-open it if they think of something I missed.
