### ISSUE TITLE
Does sexpdata use lark to parse s-expressions?

### ISSUE THREAD

**Issue by brando90** [jd-boyd/sexpdata#27]
I am curious, what is the difference between this library (https://sexpdata.readthedocs.io/en/latest/) vs using Lark (https://lark-parser.readthedocs.io/en/latest/) for parsing s-expressions?

**Comment by brando90** [comment]
related: https://github.com/lark-parser/lark/issues/634

**Comment by jd-boyd** [comment]
Sexpdata does not use lark.  Lark lets you write a s-expr parser, but it isn't a s-expr parser on its own.  I think this may predate lark being written.
