### ISSUE TITLE
Pretty printing/formatting s-expressions (s-exp sexp) as trees in Python?

### ISSUE THREAD

**Issue by brando90** [jd-boyd/sexpdata#28]

**Comment by jd-boyd** [comment]
I would be open to someone contributing this.

**Comment by fxliang** [comment]
I try it like bellow. it seems works until now. as I am not a good coder of python, it might not work always.

`
from sexpdata import *

def IsListMemberExist(lst=[]):
    try:
        typelist = [issubclass(type(l), type([])) for l in lst]
        return [False, True][True in typelist]
    except:
        return False

def _dumpss(sexp, level=0, indent = '  ', dumpslmt=32):
    if dumpslmt == 0: dumpslmt = 32
    out = '('
    inc = indent*(level+1)
    if not issubclass(type(sexp), type([])):
        out += dumps(sexp)
    else:
        for cnt in range(len(sexp)):
            e = sexp[cnt]
            if issubclass(type(e), type([])):
                if IsListMemberExist(e):
                    out += '\n' + inc
                    tmp = _dumpss(e, level+1, indent=indent)
                    out += tmp
                    if IsListMemberExist(sexp) and len(tmp) > dumpslmt:
                        out += '\n' + inc + ')'
                    else:
                        out += ')'
                else:
                    out += ' ' + dumps(e)
            else:
                if cnt != 0:
                    out += ' ' + dumps(e)
                else:
                    out += dumps(e)
                pass
    if level == 0: out += '\n)'
    return out

def dumpss(sexp, indent = '  ', dumpslmt=32):
    if dumpslmt == 0: dumpslmt = 32
    out = _dumpss(sexp, level=0, indent=indent, dumpslmt=dumpslmt)
    return out


`
