### ISSUE TITLE
Replace nosetests with pytest

### ISSUE THREAD

**Issue by jd-boyd** [jd-boyd/sexpdata#32]
nose 1 is discontinued and breaks in 3.10. nose2 is too different.

**Comment by mgorny** [comment]
I'm going to try doing it and submitting a PR today.

**Comment by ulm** [comment]
Could you tag a new release? v0.0.3 was quite a while ago?

**Comment by jd-boyd** [comment]
I've tagged 0.0.4 now.

**Comment by mgorny** [comment]
Thanks a lot!
